body:
  - type: markdown
    attributes:
      value: |
        Share your ideas for File Cleaner Pro!
        
  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem?
      placeholder: A clear description of what the problem is...
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear description of what you want to happen...
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
    validations:
      required: false
      
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here
    validations:
      required: false
